version: '3.8'

services:
  project-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://root@cockroachdb:26257/project_service?sslmode=disable
    depends_on:
      - init-db
    networks:
      - resilient-network

  cockroachdb:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - resilient-network

  init-db:
    image: cockroachdb/cockroach:latest
    depends_on:
      cockroachdb:
        condition: service_healthy
    command: >
      sql --insecure --host=cockroachdb -e "CREATE DATABASE IF NOT EXISTS project_service"
    networks:
      - resilient-network


volumes:
  cockroach-data:

networks:
  resilient-network:
